{
 "title": "Delivery Monitoring",
 "tags": [
  "zappto",
  "delivery"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Panel 1: Total Deliveries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "total_deliveries", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Panel 2: Pending Deliveries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pending_deliveries", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Panel 3: On-the-Way Deliveries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "on_the_way_deliveries", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Panel 4: Average Delivery Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "average_delivery_time_sum / average_delivery_time_count",
     "legendFormat": "average_delivery_time_sum / average_delivery_time_count"
    }
   ]
  }
 ]
}